apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  annotations:
    meta.helm.sh/release-name: jhub
    meta.helm.sh/release-namespace: jhub
  creationTimestamp: "2021-05-19T07:00:07Z"
  generation: 1
  labels:
    app: jupyterhub
    app.kubernetes.io/managed-by: Helm
    chart: jupyterhub-0.10.6
    component: user-placeholder
    heritage: Helm
    release: jhub
  name: user-placeholder
  namespace: jhub
  resourceVersion: "1793"
  uid: bb33e9b7-cf63-4f0a-9aaa-e902c6d352e6
spec:
  minAvailable: 0
  selector:
    matchLabels:
      app: jupyterhub
      component: user-placeholder
      release: jhub
status:
  currentHealthy: 0
  desiredHealthy: 0
  disruptionsAllowed: 0
  expectedPods: 0
  observedGeneration: 1
